### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by HectorTorresE** [miftah1991/Pokemon#28]
The project looks great so far. 
The pokemon cards are drawn correctly the like function works, also the counter is working.
Still, I would suggest that you guys sort the pokemons by Id before drawing the card that way the pokemon will appear in the right order. Also, at the front end of the comment section, it appears that the labels displaying the pokemon type are outside of the pop-up window.

**Comment by miftah1991** [comment]
The required issue has been solved in the new version
